### ISSUE TITLE
get_command method

### ISSUE THREAD

**Issue by gleb-svechnikov** [AndyEveritt/GcodeParser#2]
Hi, I'm trying to use your library, first of all thanks for making available it via Python Package Index.
I have an idea to to improve it a bit.
I've noticed there is a _get_param_ method, but there is not get_command method. My current task if to filter across al commands, find G1 commands and pass params farther to another method.
Do you mind if I add _get_command_ method?

**Comment by AndyEveritt** [comment]
That method could be added for sure if its useful. The reason why I didn't is you will always have a command (except for a comment), so you can just match the tuple (ie `line.command == ('G', 1)`). Whereas you are not guaranteed to have a particular parameter, so returning a default value can be useful.

If you make a pull request, I'd be happy to look through it

**Comment by gleb-svechnikov** [comment]
@AndyEveritt whan are you planning new release?

**Comment by AndyEveritt** [comment]
I will put it up tomorrow

**Comment by AndyEveritt** [comment]
New version is up
