### ISSUE TITLE
Way to calculate grams?

### ISSUE THREAD

**Issue by MajliTech** [AndyEveritt/GcodeParser#4]
How can I calculate grams from given GCode?
Thanks.

**Comment by MajliTech** [comment]
Built CuraEngine, wontfix

**Comment by AndyEveritt** [comment]
Sorry, missed this issue. You would need to use the diameter of the filament to calculate the cross sectional area of the filament. Then multiply by the Extrusion distance in the G1 command to get volume. Multiply volume by the density of the filament to get mass.
