### ISSUE TITLE
GcodeLine.gcode_str incorrect if command parameter has no associated value

### ISSUE THREAD

**Issue by amollberg** [AndyEveritt/GcodeParser#5]
Reproduction steps:
* Install gcodeparser 0.1.0
* Run python:
```
from gcodeparser import GcodeParser
p = GcodeParser("G28 W")
print(p.lines[0].gcode_str)
```
Actual: Output `G28 WTrue`
Expected: Output `G28 W`

It outputs WTrue probably because the parameter is parsed as `{'W': True}` due to the lack of a given parameter value.

**Comment by AndyEveritt** [comment]
Good catch. Will fix it in next release

**Comment by AndyEveritt** [comment]
You can use
`pip install -e "git+https://github.com/AndyEveritt/GcodeParser.git@master#egg=gcodeparser"` to use the fixed code of you don't want to wait

**Comment by AndyEveritt** [comment]
New version 0.0.9 on PyPi

**Comment by AndyEveritt** [comment]
Found a bug because `1 == True` is `True`, fixed and released new version
