### ISSUE TITLE
Does not parse codes without (G|M|T) prefix

### ISSUE THREAD

**Issue by Hatead1** [AndyEveritt/GcodeParser#9]
G code (this is a standard ISO G-code feature)

%
N0430 G01 X15.100 Z-7.742
**N0440 X12.700 Z-12.542
N0450 Z-43.151
N0460 X15.100 Z-45.551
N0470 X15.383 Z-45.834**
N0480 G00 X18.837 Z5.543
%

parsed as 
[
GcodeLine(command=('G', 1), params={'X': 15.1, 'Z': -7.742}, comment=''), 
GcodeLine(command=('G', 0), params={'X': 18.837, 'Z': 5.543}, comment='')
]

**Comment by AndyEveritt** [comment]
I haven't used that style gcode before. What would you expect the `GcodeLine` object list to be in with that example?

**Comment by Hatead1** [comment]
Most G-code commands are 'modal' 
https://www.dynomotion.com/Help/GCodeScreen/EMC_Handbook/node65.html

If a line contains only axes and other parameters, it is a continuation of the previous command. 
I think that it is necessary to save the current G|M command all the time, and if such a line comes across, output the saved G-code prefix with new coordinates/params. 

The following options are possible
G01 X15.100 Z-7.742 F2
X12.700 Z-12.542 F.5
Z1 F2

My first example must parsed as
[
GcodeLine(command=('G', 1), params={'X': 15.1, 'Z': -7.742}, comment=''),
GcodeLine(command=('G', 1), params={'X': 12.700, 'Z': -12.542}, comment=''),
GcodeLine(command=('G', 1), params={'Z': -43.151}, comment=''),
GcodeLine(command=('G', 1), params={'X': 15.100, 'Z':  -45.551}, comment=''),
GcodeLine(command=('G', 1), params={'X': 15.383, 'Z': -45.834}, comment=''),
GcodeLine(command=('G', 0), params={'X': 18.837, 'Z': 5.543}, comment='')
]

**Comment by Hatead1** [comment]
https://linuxcnc.org/docs/html/gcode/overview.html#gcode:comments - info about comments in G-code.

**Comment by AndyEveritt** [comment]
The current way I implemented the parser is using a regex expression to find all matches.
https://github.com/AndyEveritt/GcodeParser/blob/99ad01cd38547c795fb98862d76c2630760606ac/gcodeparser/gcode_parser.py#L79-L80

I can't think of an obvious way to make this work with a memory of previous commands without changing the parser to something quite different. Happy to review a PR if you want to propose something

The parser was primarily designed for FDM style gcode such as https://docs.duet3d.com/en/User_manual/Reference/Gcodes

**Comment by AndyEveritt** [comment]
If you limit it to 1 command per line then it makes it simpler as you could make a list of dicts with each parameter found on the line. Then post process the list to convert it to `GcodeLine`s. However that would break compatibility with multiple commands on a single line.
https://docs.duet3d.com/en/User_manual/Reference/Gcodes#multiple-commands-on-a-single-line

**Comment by Hatead1** [comment]
Sorry, but G-code does not require line breaks at all, all information can be written in one line even without spaces, as long as it does not contain comments starting with ‘;’

Accordingly, your regex should look through the string to find a repeating params pattern, not a one-time params pattern. 

Or add a clarification in the description that this code only works with a specific dialect and does not support the ISO standard.

**Comment by AndyEveritt** [comment]
Yes I know that you can have multiple commands on a single line, and afaik the parser currently supports that. I was just suggesting a possible solution for your problem but highlighting that it would have a caveat.

If you want to submit a pull request then I am happy to review it.
